### PR TITLE
Added API Endpoints and Files

### PR DESCRIPTION
**Pull request by emmaobiy**
1.Added new files attractions_handler.py and data-process.py.
2.Modified app.py to include three new API endpoints:
/api/attractions
/api/attraction/{attractionId}
/api/mrts.

### CODE REVIEW

**Comment by emmaobiy** [comment]
陳芝佑
http://44.237.189.163:8000/api/attractions?page=1
http://44.237.189.163:8000/api/attractions?page=0&keyword=劍潭
http://44.237.189.163:8000/api/attractions?page=0&keyword=北 
http://44.237.189.163:8000/api/attraction/10
http://44.237.189.163:8000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Name of nextPage field is incorrect.
- images field should be an array containing image URLs for each attraction, not a string.

**Comment by emmaobiy** [comment]
1.Fix name of nextPage field
2.Modify SQL query to use GROUP_CONCAT for querying images data
3.Add code to handle image URLs by converting string-formatted to array.

陳芝佑
http://44.237.189.163:8000/api/attractions?page=1
http://44.237.189.163:8000/api/attractions?page=0&keyword=劍潭
http://44.237.189.163:8000/api/attractions?page=0&keyword=北 
http://44.237.189.163:8000/api/attraction/10
http://44.237.189.163:8000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should not get all attraction data from database and do pagination by our own code.(how about 1,000,000 rows) We should use SQL Limit feature to do pagination directly.

**Comment by emmaobiy** [comment]
Modify to utilize SQL LIMIT feature for pagination and integrate SQL execution statements.

陳芝佑
http://44.237.189.163:8000/api/attractions?page=1
http://44.237.189.163:8000/api/attractions?page=0&keyword=劍潭
http://44.237.189.163:8000/api/attractions?page=0&keyword=北
http://44.237.189.163:8000/api/attraction/10
http://44.237.189.163:8000/api/mrts

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
